### ISSUE TITLE
naemon fails to build on fedora 28

### ISSUE THREAD

**Issue by sni** [naemon/naemon-core#228]
naemon fails to build with fedora 28 (that is gcc 8.1.1)

```
src/naemon/objects_host.c: In function 'create_host':
src/naemon/objects_host.c:72:42: error: cast between incompatible function types from 'int (*)(const char *, const char *)' to 'gint (*)(const void *, const void *, void *)' {aka 'int (*)(const void *, const void *, void *)'} [-Werror=cast-function-type]
  new_host->child_hosts = g_tree_new_full((GCompareDataFunc)g_strcmp0, NULL, g_free, NULL);
                                          ^
src/naemon/objects_host.c:73:43: error: cast between incompatible function types from 'int (*)(const char *, const char *)' to 'gint (*)(const void *, const void *, void *)' {aka 'int (*)(const void *, const void *, void *)'} [-Werror=cast-function-type]
  new_host->parent_hosts = g_tree_new_full((GCompareDataFunc)g_strcmp0, NULL, g_free, NULL);
                                           ^
cc1: all warnings being treated as errors
```
