### ISSUE TITLE
naemon fails to build on ubuntu 17.10 (i386)

### ISSUE THREAD

**Issue by sni** [naemon/naemon-core#229]
naemon fails to build on a 32bit ubuntu 17.10

```
src/naemon/objects_timeperiod.c:289:26: error: '%02d' directive writing between 2 and 7 bytes into a region of size between 1 and 6 [-Werror=format-overflow=]
  sprintf(str, "%02d:%02d-%02d:%02d", sh, sm, eh, em);
                          ^~~~
src/naemon/objects_timeperiod.c:289:15: note: directive argument in the range [0, 1193046]
  sprintf(str, "%02d:%02d-%02d:%02d", sh, sm, eh, em);
               ^~~~~~~~~~~~~~~~~~~~~
src/naemon/objects_timeperiod.c:289:15: note: directive argument in the range [0, 59]
In file included from /usr/include/stdio.h:862:0,
                 from src/naemon/objects_common.h:10,
                 from src/naemon/objects_timeperiod.h:11,
                 from src/naemon/objects_timeperiod.c:1:
/usr/include/i386-linux-gnu/bits/stdio2.h:33:10: note: '__builtin___sprintf_chk' output between 12 and 22 bytes into a destination of size 12
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:1855: recipe for target 'src/naemon/objects_timeperiod.lo' failed
```
